import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import AuthProvider from "../providers/AuthProvider";
import styles from "./auth.module.css";
import "../globals.css";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
const sourceSans3 = Source_Sans_3({
    subsets: ["latin"],
    display: "swap", // or 'fallback', 'optional', 'block'
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={sourceSans3.className}>
            <body className={styles.body}>
                <AuthProvider>
                    <div className={styles.container}>
                        <header className={styles.header}>
                            <Navbar />
                        </header>

                        <main className={styles.main}>{children}</main>

                        <Footer />
                    </div>
                </AuthProvider>
            </body>
        </html>
    );
}
