import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Source_Sans_3 } from 'next/font/google';
import "./container.css"
// import "../globals.css";
// import Header from "../components/header";
import Featured from "../components/featured/featured";
import Navbar from "../components/navbar/navbar"
import Footer from "../components/footer/footer";
import AuthProvider from "../providers/AuthProvider";
// import { Provider } from "@/components/ui/provider"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const sourceSans3 = Source_Sans_3({
  subsets: ['latin'],
  display: 'swap', // or 'fallback', 'optional', 'block'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sourceSans3.className} >
      <body>
        <AuthProvider>
          <div className="container">
            <Navbar />
            <hr className="line" />
        
            {children}
            <Footer />
          </div>
        </AuthProvider>
            
        

      </body>
    </html>
  );
}
