import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import AuthProvider from "../providers/AuthProvider";
import styles from "./home.module.css";
import "../globals.css";
import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar/navbar";
const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  display: "swap", // or 'fallback', 'optional', 'block'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sourceSans3.className}>
      <body className={styles.body}>
        <AuthProvider>
          <div className={styles.container}>
            <div className={styles.header}>
              <Navbar />
            </div>

            <div className={styles.main}>{children}</div>

            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
